# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87642ce71d327faedc62fa93bc22b97ab1030746453bc4e5a52098afd13816d66839af9b957747089a53a50df9ac1cda00b4dd80e6414303e8e00f00caab8d6c

test:
  secret_key_base: 7f47925afbd242b6cebd7ccf41556757a73c967fd02451de7ce2b360b40cbadaef00f2e50d4edcecdfb971f0d5932df142815d38b7c1d1d24466a3bc0d5ca811

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
